// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA043rAB4uu6s8RsTfMXYDH27pNAVHV2OA',
    appId: '1:948709744510:web:c5b605080e1f5151e91d2f',
    messagingSenderId: '948709744510',
    projectId: 'firestorageakshy',
    authDomain: 'firestorageakshy.firebaseapp.com',
    storageBucket: 'firestorageakshy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPkh0rQILmMc0CVbh7OdKb54x7BF3ZdE',
    appId: '1:948709744510:android:05f07de3045e33f9e91d2f',
    messagingSenderId: '948709744510',
    projectId: 'firestorageakshy',
    storageBucket: 'firestorageakshy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7J4ZTrR5xfIiWTHXATOZMSR5iqmMMvQ',
    appId: '1:948709744510:ios:12f602d1caea6443e91d2f',
    messagingSenderId: '948709744510',
    projectId: 'firestorageakshy',
    storageBucket: 'firestorageakshy.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD7J4ZTrR5xfIiWTHXATOZMSR5iqmMMvQ',
    appId: '1:948709744510:ios:12f602d1caea6443e91d2f',
    messagingSenderId: '948709744510',
    projectId: 'firestorageakshy',
    storageBucket: 'firestorageakshy.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA043rAB4uu6s8RsTfMXYDH27pNAVHV2OA',
    appId: '1:948709744510:web:821f4a123c605f62e91d2f',
    messagingSenderId: '948709744510',
    projectId: 'firestorageakshy',
    authDomain: 'firestorageakshy.firebaseapp.com',
    storageBucket: 'firestorageakshy.appspot.com',
  );
}
